SELECT * FROM SC6990 WHERE C6_PRODUTO ='0000002020'

SELECT TABELAS.NAME, COLUNAS.NAME AS COLUNA ,TIPOS.NAME AS TIPO, COLUNAS.LENGTH AS TAMANHO ,COLUNAS.ISNULLABLE AS EHNULO
FROM sysobjects as TABELAS, syscolumns AS COLUNAS, systypes as TIPOS
WHERE TABELAS.ID = COLUNAS.ID AND COLUNAS.usertype = TIPOS.usertype AND TABELAS.NAME = 'se1990'

SELECT D1_PEDIDO,
D1_ITEMPC ,* FROM SD1990

SELECT * FROM SE1990 where A6_COD = '341'  AND 
A6_AGENCIA = '0001' AND  A6_NUMCON = '000001'
	
select e1_conta,* from SE1990
